### ISSUE TITLE
IMVDB providerID not saved when result found via search.

### ISSUE THREAD

**Issue by SenorSmartyPants** [crobibero/jellyfin-plugin-imvdb#2]
Scan a video file with no metadata (especially no IMVDB ID). Results are found correctly, but IMVDB ID is not saved.

When searching via an existing IMVDB ID that ID is saved back to the item again

https://github.com/crobibero/jellyfin-plugin-imvdb/blob/e748114160b2b571859457bcbf65dee29ada90f5/Jellyfin.Plugin.IMVDb/ImvdbProvider.cs#L104

**Comment by crobibero** [comment]
Added in `2.2021.405.46`
