### ISSUE TITLE
Image Info downloaded, but plugin is not an image provider

### ISSUE THREAD

**Issue by SenorSmartyPants** [crobibero/jellyfin-plugin-imvdb#3]
Plugin is parsing image info provided by IMVDB but plugin does not expose image provider functionality.

Please make plugin a image provider for metadata type MusicVideo as well.

**Comment by crobibero** [comment]
Added in `2.2021.405.46`

**Comment by SenorSmartyPants** [comment]
Thank you so much for all these quick fixes. Plugin is working great now.
