### ISSUE TITLE
Possible to save external URL to IMVDB?

### ISSUE THREAD

**Issue by SenorSmartyPants** [crobibero/jellyfin-plugin-imvdb#5]
I realize the IMVDB ID is not used in the URL, they provide slugs instead in the API return data. Is it possible to save those URLs to the JF item? Or are ExternalURLs generated programmatically from the IDs only?

Would be nice to have that link to IMVDB if possible, but no big deal if it's not. I don't see a way to add them manually in Edit Metadata either.

**Comment by crobibero** [comment]
Fixed in `2.2021.406.119`
The `entites` API is currently returning a 500 so I wasn't able to properly test, but it should work if the endpoint decides to work.

**Comment by SenorSmartyPants** [comment]
Seems to work fine. IMVDB links show up on videos and directors. Not seeing it for Duran Duran Artist ATM.

One suggestion would be to alter one of the labels on the IMVDB ID fields to help differentiate between them.

![image](https://user-images.githubusercontent.com/991618/113656950-8d81fd80-9662-11eb-9dcc-73edaebd9780.png)

**Comment by crobibero** [comment]
I tried that but it uses the name of the id to display the link, so I’m not sure what to name it

**Comment by SenorSmartyPants** [comment]
TMDB plugin does it somehow

![image](https://user-images.githubusercontent.com/991618/113657579-dc7c6280-9663-11eb-834e-da3831481fe3.png)

![image](https://user-images.githubusercontent.com/991618/113657548-cc648300-9663-11eb-9e5b-6fdb9d344b92.png)

**Comment by crobibero** [comment]
Perfect thanks I’ll use that as reference when I have time

**Comment by crobibero** [comment]
![image](https://user-images.githubusercontent.com/24963659/113791607-48f96f00-9701-11eb-9c8a-8f9bd1292f68.png)

I think this is the best I can do. The `ReleaseGroup` is an enum and has limited selection so I picked one that doesn't mean anything

**Comment by crobibero** [comment]
Released in `2.2021.406.2357`

**Comment by SenorSmartyPants** [comment]
Good enough for me.
