### ISSUE TITLE
Cloud storage provider is flagged as containing harmful programs on Chrome

### ISSUE THREAD

**Issue by chenichadowitz** [crobibero/jellyfin-plugin-imvdb#6]
The manifest url for crobibero's plugin repo is listed as https://repo.codyrobibero.dev/manifest.json but if you actually browse there (at least in Chrome), it redirects you to https://s3.wasabisys.com/jellyfin-plugin-repo/manifest.json which is currently flagged on Chrome as containing harmful programs. 

It looks like wasabisys.com is a cloud storage provider so it's likely that it's simply other wasabisys users hosting harmful files on the same domain, but in that case it may be worth hosting elsewhere to avoid the issue.
![image](https://user-images.githubusercontent.com/3758336/114890057-b0d24880-9dd8-11eb-9c8f-52c1f90bb361.png)

**Comment by crobibero** [comment]
Amazing, thanks for the heads up. I’ll look into migrating to a different host

**Comment by crobibero** [comment]
I just installed chrome to test, I don't have this issue, even with "enhanced protection" enabled, so I don't think this is actually an issue?

The repo might still end up being relocated eventually, but as of right now this isn't a priority

**Comment by chenichadowitz** [comment]
Strange - I just tried both urls I included in the original issue and neither have the issue any longer. Maybe it was a transient thing or a bug on Google/Chrome's side. Thanks for checking anyways!
